name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  daemon:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd ./daemon
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./daemon
        cargo test --verbose

  server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd ./server
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./server
        cargo test --verbose

  client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd ./client
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./client
        cargo test --verbose
